import type { ToolDefinition } from "./types";

export const imageTools: ToolDefinition[] = [
  {
    slug: "image-compressor",
    name: "Image Compressor",
    tagline: "Reduce image file sizes without losing visible quality.",
    icon: "Image",
    category: "Images",
  },
  {
    slug: "image-resize",
    name: "Resize & Convert",
    tagline: "Resize images and convert between JPG, PNG, and WebP.",
    icon: "Crop",
    category: "Images",
  },
  {
    slug: "svg-optimizer",
    name: "SVG Optimizer",
    tagline: "Strip massive paths and bloat from SVGs to dramatically reduce file sizes.",
    icon: "Scissors",
    category: "Images",
  },
  {
    slug: "image-watermarker",
    name: "Image Watermarker",
    tagline: "Stamp text or logo watermarks onto images with full position control.",
    icon: "Stamp",
    category: "Images",
  },
  {
    slug: "image-metadata",
    name: "Image Metadata",
    tagline: "Inspect EXIF, IPTC, ICC, and GPS metadata embedded in your images.",
    icon: "ScanSearch",
    category: "Images",
  },
  {
    slug: "image-rotate",
    name: "Rotate & Flip",
    tagline: "Rotate images by any angle and flip horizontally or vertically.",
    icon: "RotateCw",
    category: "Images",
  },
  {
    slug: "image-color-picker",
    name: "Color Picker",
    tagline: "Pick any color from an image and get HEX, RGB, and HSL values.",
    icon: "Pipette",
    category: "Images",
  },
  {
    slug: "image-base64",
    name: "Image ↔ Base64",
    tagline: "Encode images to Base64 data URIs and decode them back.",
    icon: "Binary",
    category: "Images",
  },
  {
    slug: "image-placeholder",
    name: "Placeholder Generator",
    tagline: "Generate colored or textured placeholder images at any size.",
    icon: "Square",
    category: "Images",
  },
  {
    slug: "image-crop",
    name: "Image Crop",
    tagline: "Visually crop images with free or locked aspect ratios.",
    icon: "Crop",
    category: "Images",
  },
  {
    slug: "image-filters",
    name: "Filters & Effects",
    tagline: "Apply brightness, contrast, blur, sepia, grayscale, and more.",
    icon: "Sparkles",
    category: "Images",
  },
  {
    slug: "image-format-converter",
    name: "Format Converter",
    tagline: "Convert between JPG, PNG, WebP, BMP, TIFF, and AVIF.",
    icon: "ArrowLeftRight",
    category: "Images",
  },
  {
    slug: "image-favicon",
    name: "Favicon Generator",
    tagline: "Create multi-size favicons and apple-touch-icons from any image.",
    icon: "Globe",
    category: "Images",
  },
  {
    slug: "image-info",
    name: "Image Info Viewer",
    tagline: "View DPI, color space, file size, dimensions, and ICC profile.",
    icon: "Info",
    category: "Images",
  },
  {
    slug: "image-gif-maker",
    name: "GIF Maker",
    tagline: "Create animated GIFs from a sequence of images.",
    icon: "Film",
    category: "Images",
  },
  {
    slug: "image-gif-extractor",
    name: "GIF Frame Extractor",
    tagline: "Extract individual frames from animated GIFs as PNG images.",
    icon: "Images",
    category: "Images",
  },
  {
    slug: "image-gif-optimizer",
    name: "GIF Optimizer",
    tagline: "Reduce GIF file size by optimizing colors and frames.",
    icon: "Minimize2",
    category: "Images",
  },
  {
    slug: "image-drop-shadow",
    name: "Drop Shadow",
    tagline: "Add configurable drop shadows to images with full control.",
    icon: "Droplets",
    category: "Images",
  },
  {
    slug: "image-border",
    name: "Image Border",
    tagline: "Add decorative borders, frames, and rounded corners to images.",
    icon: "Frame",
    category: "Images",
  },
  {
    slug: "image-overlay",
    name: "Image Overlay",
    tagline: "Layer one image on another with opacity and blend modes.",
    icon: "Layers",
    category: "Images",
  },
  {
    slug: "image-comparator",
    name: "Image Diff",
    tagline: "Compare two images side-by-side, overlay, or pixel diff.",
    icon: "GitCompare",
    category: "Images",
  },
  {
    slug: "image-histogram",
    name: "Image Histogram",
    tagline: "View RGB and luminance channel distributions of an image.",
    icon: "BarChart3",
    category: "Images",
  },
  {
    slug: "image-collage",
    name: "Collage Maker",
    tagline: "Combine multiple photos into a beautiful collage layout.",
    icon: "LayoutGrid",
    category: "Images",
  },
  {
    slug: "image-annotate",
    name: "Image Annotate",
    tagline: "Draw arrows, shapes, and text on images with full control.",
    icon: "PenTool",
    category: "Images",
  },
  {
    slug: "image-social-resizer",
    name: "Social Media Resizer",
    tagline: "Resize images to exact dimensions for Instagram, X, LinkedIn, and more.",
    icon: "Share2",
    category: "Images",
  },
  {
    slug: "image-profile-pic",
    name: "Profile Picture Maker",
    tagline: "Crop any photo into a perfect circle or square profile picture.",
    icon: "User",
    category: "Images",
  },
  {
    slug: "image-meme",
    name: "Meme Generator",
    tagline: "Add top and bottom text to images with font controls.",
    icon: "Laugh",
    category: "Images",
  },
  {
    slug: "image-qr-reader",
    name: "QR Code Reader",
    tagline: "Scan and decode QR codes from images.",
    icon: "ScanLine",
    category: "Images",
  },
  {
    slug: "image-barcode",
    name: "Barcode Generator",
    tagline: "Generate barcodes in Code128, EAN-13, and more formats.",
    icon: "Barcode",
    category: "Images",
  },
  {
    slug: "image-exif-stripper",
    name: "EXIF Stripper",
    tagline: "Remove all EXIF metadata (GPS, camera info) before sharing.",
    icon: "Shield",
    category: "Images",
  },
  {
    slug: "image-css-sprite",
    name: "CSS Sprite Generator",
    tagline: "Combine images into a sprite sheet with auto-generated CSS.",
    icon: "Grid3x3",
    category: "Images",
  },
  {
    slug: "image-html-to-image",
    name: "HTML to Image",
    tagline: "Screenshot any HTML snippet as a PNG image.",
    icon: "Camera",
    category: "Images",
  },
  {
    slug: "image-lazy-placeholder",
    name: "Lazy Load Placeholder",
    tagline: "Generate tiny blurred thumbnails for lazy loading.",
    icon: "CloudFog",
    category: "Images",
  },
  {
    slug: "image-ascii",
    name: "Image to ASCII Art",
    tagline: "Convert any image into text-based ASCII art.",
    icon: "Terminal",
    category: "Images",
  },
  {
    slug: "image-steganography",
    name: "Steganography",
    tagline: "Hide secret text data inside images using LSB encoding.",
    icon: "EyeOff",
    category: "Images",
  },
  {
    slug: "image-ocr",
    name: "OCR Text Recognition",
    tagline: "Extract text from images in 10+ languages using Tesseract.js.",
    icon: "FileText",
    category: "Images",
  },
  {
    slug: "image-ai-upscaler",
    name: "AI Image Upscaler",
    tagline: "Upscale images 2x using neural network inference in the browser.",
    icon: "Maximize",
    category: "Images",
  },
];
