import type { ToolDefinition } from "./types";

export const pdfTools: ToolDefinition[] = [
  {
    slug: "pdf-merger",
    name: "PDF Merger",
    tagline: "Combine multiple PDF documents into a single file.",
    icon: "FileDown",
    category: "PDF",
  },
  {
    slug: "pdf-split",
    name: "PDF Split",
    tagline: "Split a PDF by page ranges or extract individual pages.",
    icon: "Scissors",
    category: "PDF",
  },
  {
    slug: "pdf-rotate",
    name: "PDF Rotate",
    tagline: "Rotate pages by 90° increments, individually or all at once.",
    icon: "RotateCw",
    category: "PDF",
  },
  {
    slug: "pdf-remove-pages",
    name: "PDF Page Remover",
    tagline: "Remove unwanted pages from your PDF.",
    icon: "FileX2",
    category: "PDF",
  },
  {
    slug: "pdf-lock",
    name: "PDF Lock / Unlock",
    tagline: "Protect a PDF with a password or remove its protection.",
    icon: "LockKeyhole",
    category: "PDF",
  },
  {
    slug: "pdf-compressor",
    name: "PDF Compressor",
    tagline: "Reduce PDF file sizes locally with structural optimization.",
    icon: "FileArchive",
    category: "PDF",
  },
  {
    slug: "pdf-watermark",
    name: "PDF Watermark",
    tagline: "Stamp text or image watermarks onto PDF pages.",
    icon: "Stamp",
    category: "PDF",
  },
  {
    slug: "pdf-page-numbers",
    name: "Add Page Numbers",
    tagline: "Automatically stamp sequential page numbers across a document.",
    icon: "ListOrdered",
    category: "PDF",
  },
  {
    slug: "pdf-metadata",
    name: "PDF Metadata Editor",
    tagline: "View and modify hidden PDF metadata (Title, Author, Subject).",
    icon: "ScanSearch",
    category: "PDF",
  },
  {
    slug: "pdf-organize",
    name: "Organize PDF",
    tagline: "Visually reorder pages in a PDF using drag-and-drop.",
    icon: "LayoutGrid",
    category: "PDF",
  },
  {
    slug: "pdf-signer",
    name: "PDF Signer",
    tagline: "Draw, type, or upload a signature and stamp it onto a PDF.",
    icon: "PenTool",
    category: "PDF",
  },
  {
    slug: "pdf-extract-images",
    name: "Extract PDF Images",
    tagline: "Extract all embedded JPEGs and PNGs from a PDF into a ZIP file.",
    icon: "Image",
    category: "PDF",
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    tagline: "Extract raw text from a PDF document.",
    icon: "FileText",
    category: "PDF",
  },
  {
    slug: "pdf-cropper",
    name: "PDF Cropper",
    tagline: "Crop margins visually from all pages.",
    icon: "Crop",
    category: "PDF",
  },
  {
    slug: "pdf-flatten",
    name: "Flatten PDF",
    tagline: "Burn interactive form fields into the document.",
    icon: "Layers",
    category: "PDF",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    tagline: "Combine multiple images into a single PDF document.",
    icon: "FileImage",
    category: "PDF",
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    tagline: "Convert PDF pages to high-quality images (PNG, JPEG, WebP) with customizable DPI and quality.",
    icon: "FileImage",
    category: "PDF",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    tagline: "Convert DOCX documents to PDF locally in your browser.",
    icon: "FileText",
    category: "PDF",
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    tagline: "Convert HTML code to PDF using the browser print API.",
    icon: "Globe",
    category: "PDF",
  },
  {
    slug: "csv-to-pdf",
    name: "CSV to PDF",
    tagline: "Convert CSV data into a formatted PDF table.",
    icon: "Table",
    category: "PDF",
  },
  {
    slug: "markdown-to-pdf",
    name: "Markdown to PDF",
    tagline: "Write Markdown and convert it to a downloadable PDF.",
    icon: "FileCode",
    category: "PDF",
  },
  {
    slug: "pdf-to-markdown",
    name: "PDF to Markdown",
    tagline: "Extract text from a PDF and format it as Markdown.",
    icon: "FileText",
    category: "PDF",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    tagline: "Convert CSV/Excel files to formatted PDF tables.",
    icon: "Table",
    category: "PDF",
  },
];
