import type { ToolDefinition } from "./types";

export const videoAudioTools: ToolDefinition[] = [
  {
    slug: "media-converter",
    name: "Media Converter",
    tagline: "Convert between video and audio formats (MP4, MP3, GIF) locally in your browser.",
    icon: "Film",
    category: "Video & Audio",
  },
  {
    slug: "video-to-gif",
    name: "Video to GIF",
    tagline: "Convert video clips to animated GIFs with custom FPS, dimensions, and timing.",
    icon: "Film",
    category: "Video & Audio",
  },
  {
    slug: "video-to-images",
    name: "Video to Images",
    tagline: "Extract frames from a video as PNG or JPG images at any frame rate.",
    icon: "Images",
    category: "Video & Audio",
  },
  {
    slug: "gif-to-video",
    name: "GIF to Video",
    tagline: "Convert animated GIFs to MP4 or WebM video files for smaller sizes and better compatibility.",
    icon: "Play",
    category: "Video & Audio",
  },
  {
    slug: "video-rotator",
    name: "Video Rotator",
    tagline: "Rotate or flip videos by 90°, 180°, 270°, or mirror horizontally/vertically.",
    icon: "RotateCw",
    category: "Video & Audio",
  },
  {
    slug: "video-mute",
    name: "Video Mute",
    tagline: "Remove the audio track from any video file while keeping the video intact.",
    icon: "VolumeX",
    category: "Video & Audio",
  },
  {
    slug: "video-resizer",
    name: "Video Resizer",
    tagline: "Resize video dimensions to any width and height with optional aspect ratio lock.",
    icon: "Maximize",
    category: "Video & Audio",
  },
  {
    slug: "video-to-audio",
    name: "Video to Audio",
    tagline: "Extract audio from video files as MP3, WAV, AAC, or OGG.",
    icon: "Music",
    category: "Video & Audio",
  },
  {
    slug: "audio-trimmer",
    name: "Audio Trimmer",
    tagline: "Trim audio files by setting start time and duration using FFmpeg.",
    icon: "Scissors",
    category: "Video & Audio",
  },
  {
    slug: "audio-converter",
    name: "Audio Format Converter",
    tagline: "Convert between MP3, WAV, OGG, AAC, and FLAC audio formats.",
    icon: "ArrowLeftRight",
    category: "Video & Audio",
  },
  {
    slug: "audio-speed",
    name: "Audio Speed Changer",
    tagline: "Speed up or slow down audio files (0.25x to 4x) using FFmpeg.",
    icon: "Gauge",
    category: "Video & Audio",
  },
];
